main: net.zeeraa.terrasmp.terrasmp.TerraSMP
name: TerraSMP
description: TerraSMP Plugin
version: 1.0
depend: [NovaCore, Factions]

permissions:
   terrasmp.sign.selectcontinent:
      description: Access to creating continent selector signs
      default: op